@extends('layouts.platform')

@section('title', __('platform.subscriptions.page_title') . ' · ' . __('platform.brand'))

@section('content')
    @php
        $statusLabels = __('platform.subscriptions.statuses');
        $money = static fn (mixed $minor): string => number_format(((int) $minor) / 100, 2, '.', ',');
        $limit = static fn (mixed $value): string => $value === null ? '∞' : (string) $value;
        $datetime = static fn (mixed $value): string => $value ? \Illuminate\Support\Carbon::parse($value)->timezone('Africa/Cairo')->format('Y-m-d H:i') : '—';
    @endphp
    <main class="mx-auto min-h-screen max-w-[1440px] px-4 py-6 sm:px-6 lg:px-8">
        <header class="flex flex-wrap items-start justify-between gap-5 border-b border-[var(--pn-border)] pb-5">
            <div><p class="text-sm font-semibold text-[var(--pn-primary)]">{{ __('platform.brand') }}</p><p class="mt-1 text-sm text-[var(--pn-ink-muted)]">{{ __('platform.platform_label') }}</p><h1 class="mt-4 text-2xl font-bold">{{ __('platform.subscriptions.page_title') }}</h1><p class="mt-1 max-w-3xl text-sm leading-6 text-[var(--pn-ink-muted)]">{{ __('platform.subscriptions.page_description') }}</p></div>
            <div class="flex flex-wrap gap-3"><a class="inline-flex min-h-11 items-center rounded-[10px] border border-[var(--pn-border-strong)] px-4 text-sm font-semibold hover:bg-[var(--pn-surface-subtle)]" href="{{ route('platform.plans.index') }}">{{ __('platform.subscriptions.plans') }}</a><a class="inline-flex min-h-11 items-center rounded-[10px] border border-[var(--pn-border-strong)] px-4 text-sm font-semibold hover:bg-[var(--pn-surface-subtle)]" href="{{ route('platform.tenants.index') }}">{{ __('platform.subscriptions.tenants') }}</a><form method="POST" action="{{ route('platform.logout') }}">@csrf<button class="min-h-11 rounded-[10px] border border-[var(--pn-border-strong)] px-4 text-sm font-semibold hover:bg-[var(--pn-surface-subtle)]" type="submit">{{ __('platform.plans.sign_out') }}</button></form></div>
        </header>
        @if (session('success')) <div class="mt-5 rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-success-soft)] px-4 py-3 font-semibold text-[var(--pn-success)]" role="status">{{ session('success') }}</div> @endif
        @if ($errors->any()) <div class="mt-5 rounded-[10px] border border-[var(--pn-danger)] bg-[var(--pn-danger-soft)] px-4 py-3 text-[var(--pn-danger)]" role="alert"><p class="font-semibold">{{ __('platform.subscriptions.validation_failed') }}</p><ul class="mt-2 list-inside list-disc text-sm">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif

        <section class="mt-8 rounded-[14px] border border-[var(--pn-border)] bg-[var(--pn-surface)] p-5 shadow-sm" aria-labelledby="assign-subscription-heading">
            <h2 class="text-lg font-bold" id="assign-subscription-heading">{{ __('platform.subscriptions.assign_heading') }}</h2><p class="mt-1 max-w-3xl text-sm text-[var(--pn-ink-muted)]">{{ __('platform.subscriptions.assign_description') }}</p>
            <form class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4" method="POST" action="{{ route('platform.subscriptions.assign', ['tenant' => '__TENANT__']) }}" data-subscription-assign-form>
                @csrf @method('PATCH')<input type="hidden" name="expected_current_subscription_id" value="" data-assign-current-subscription>
                <div><label class="block text-sm font-semibold" for="assign-tenant">{{ __('platform.subscriptions.tenant') }}</label><select class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-3" id="assign-tenant" name="tenant_id" data-assign-tenant required><option value="">—</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" data-current-subscription="{{ $tenant->current_subscription_id }}">{{ $tenant->name }} ({{ $tenant->internal_identifier }})</option>@endforeach</select></div>
                <div><label class="block text-sm font-semibold" for="assign-plan">{{ __('platform.subscriptions.plan') }}</label><select class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-3" id="assign-plan" name="plan_id" required><option value="">—</option>@foreach($plans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }} ({{ $plan->code }})</option>@endforeach</select></div>
                <div><label class="block text-sm font-semibold" for="assign-interval">{{ __('platform.subscriptions.interval') }}</label><select class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-3" id="assign-interval" name="billing_interval"><option value="monthly">{{ __('platform.subscriptions.monthly') }}</option><option value="yearly">{{ __('platform.subscriptions.yearly') }}</option></select></div>
                <div><label class="block text-sm font-semibold" for="assign-reason">{{ __('platform.subscriptions.reason') }}</label><input class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-3" id="assign-reason" name="reason" required></div>
                <input type="hidden" name="status" value="trialing"><button class="inline-flex min-h-11 items-center justify-center rounded-[10px] bg-[var(--pn-primary)] px-4 font-semibold text-[var(--pn-surface)]" type="submit">{{ __('platform.subscriptions.assign') }}</button>
            </form>
        </section>

        <section class="mt-8" aria-labelledby="subscriptions-heading">
            <form class="flex flex-wrap items-end gap-3" method="GET"><div><label class="block text-sm font-semibold" for="subscription-search">{{ __('platform.subscriptions.search') }}</label><input class="mt-2 min-h-11 rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-3" id="subscription-search" name="q" value="{{ $filters['q'] }}"></div><div><label class="block text-sm font-semibold" for="subscription-status-filter">{{ __('platform.subscriptions.status') }}</label><select class="mt-2 min-h-11 rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-3" id="subscription-status-filter" name="status"><option value="">{{ __('platform.subscriptions.all_statuses') }}</option>@foreach($statusLabels as $key => $label)<option value="{{ $key }}" @selected($filters['status'] === $key)>{{ $label }}</option>@endforeach</select></div><button class="min-h-11 rounded-[10px] border border-[var(--pn-border-strong)] px-4 font-semibold" type="submit">{{ __('platform.subscriptions.filter') }}</button></form>
            @if($subscriptions->isEmpty()) <div class="mt-4 rounded-[14px] border border-[var(--pn-border)] bg-[var(--pn-surface)] p-6 text-[var(--pn-ink-muted)]">{{ __('platform.subscriptions.empty') }}</div>
            @else <div class="mt-4 overflow-x-auto rounded-[14px] border border-[var(--pn-border)] bg-[var(--pn-surface)] shadow-sm"><table class="w-full text-start text-sm"><thead class="border-b border-[var(--pn-border)] bg-[var(--pn-surface-subtle)]"><tr><th class="px-4 py-3">{{ __('platform.subscriptions.tenant') }}</th><th class="px-4 py-3">{{ __('platform.subscriptions.plan') }}</th><th class="px-4 py-3">{{ __('platform.subscriptions.status') }}</th><th class="px-4 py-3">{{ __('platform.subscriptions.trial_end') }}</th><th class="px-4 py-3">{{ __('platform.subscriptions.limits_usage') }}</th><th class="px-4 py-3">{{ __('platform.subscriptions.actions') }}</th></tr></thead><tbody class="divide-y divide-[var(--pn-border)]">
                @foreach($subscriptions as $subscription) @php($summary = $summaries[$subscription->id]) @php($isCurrent = (int) $subscription->tenant?->current_subscription_id === (int) $subscription->id) <tr class="align-top"><th class="px-4 py-4 text-start font-semibold">{{ $subscription->tenant?->name }}</th><td class="px-4 py-4">{{ $subscription->plan?->name }}<span class="block tabular-nums text-xs text-[var(--pn-ink-muted)]"><bdi dir="ltr">{{ $money($subscription->price_amount_minor) }} {{ $subscription->price_currency }}</bdi> · {{ __('platform.subscriptions.'.$subscription->billing_interval) }}</span></td><td class="px-4 py-4"><span class="font-semibold">{{ $statusLabels[$subscription->status] ?? $subscription->status }}</span><span class="mt-1 block text-xs text-[var(--pn-ink-muted)]">{{ __('platform.subscriptions.phases.'.$summary['phase']) }}</span></td><td class="px-4 py-4 tabular-nums">{{ $datetime($subscription->trial_ends_at) }}<span class="mt-1 block text-xs text-[var(--pn-ink-muted)]">{{ __('platform.subscriptions.period_end') }}: {{ $datetime($subscription->current_period_ends_at) }}</span></td><td class="px-4 py-4 tabular-nums"><div>{{ $summary['branch_usage'] }}/{{ $limit($summary['branch_limit']) }} {{ __('platform.plans.branches_short') }}</div><div>{{ $summary['user_usage'] }}/{{ $limit($summary['user_limit']) }} {{ __('platform.plans.users_short') }}</div>@if(($summary['branch_limit'] !== null && $summary['branch_usage'] > $summary['branch_limit']) || ($summary['user_limit'] !== null && $summary['user_usage'] > $summary['user_limit']))<span class="mt-1 inline-block font-semibold text-[var(--pn-danger)]">{{ __('platform.subscriptions.over_limit') }}</span>@endif</td><td class="px-4 py-4">@if($isCurrent)<details><summary class="cursor-pointer font-semibold text-[var(--pn-primary)]">{{ __('platform.subscriptions.actions') }}</summary><div class="mt-3 min-w-[280px] space-y-3 rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface-subtle)] p-3">
                    <form method="POST" action="{{ route('platform.subscriptions.status', $subscription) }}">@csrf @method('PATCH')<input type="hidden" name="expected_status" value="{{ $subscription->status }}"><label class="block text-xs font-semibold">{{ __('platform.subscriptions.change_status') }}</label><select class="mt-1 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="status">@foreach($statusLabels as $key => $label)<option value="{{ $key }}" @selected($key === $subscription->status)>{{ $label }}</option>@endforeach</select><input class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="reason" placeholder="{{ __('platform.subscriptions.reason') }}" required><button class="mt-2 min-h-11 rounded-[10px] border border-[var(--pn-border-strong)] px-3 font-semibold" type="submit">{{ __('platform.subscriptions.save') }}</button></form>
                    <form method="POST" action="{{ route('platform.subscriptions.trial', $subscription) }}">@csrf<label class="block text-xs font-semibold">{{ __('platform.subscriptions.extend_trial') }}</label><input class="mt-1 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="trial_ends_at" type="datetime-local" required><input class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="reason" placeholder="{{ __('platform.subscriptions.reason') }}" required><button class="mt-2 min-h-11 rounded-[10px] border border-[var(--pn-border-strong)] px-3 font-semibold" type="submit">{{ __('platform.subscriptions.extend_trial') }}</button></form>
                    <form method="POST" action="{{ route('platform.subscriptions.limits', $subscription) }}">@csrf @method('PATCH')<label class="block text-xs font-semibold">{{ __('platform.subscriptions.override_limits') }}</label><div class="mt-1 grid grid-cols-2 gap-2"><input class="min-h-11 rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="custom_limits[branches]" type="number" min="1" placeholder="{{ __('platform.subscriptions.branch_limit') }}" value="{{ data_get($subscription->custom_limits_json, 'branches') }}"><input class="min-h-11 rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="custom_limits[users]" type="number" min="1" placeholder="{{ __('platform.subscriptions.user_limit') }}" value="{{ data_get($subscription->custom_limits_json, 'users') }}"></div><input class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="override_until" type="datetime-local" value="{{ $subscription->custom_limits_override_until?->format('Y-m-d\\TH:i') }}"><input class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="reason" placeholder="{{ __('platform.subscriptions.reason') }}" required><button class="mt-2 min-h-11 rounded-[10px] border border-[var(--pn-border-strong)] px-3 font-semibold" type="submit">{{ __('platform.subscriptions.save') }}</button></form>
                    <form method="POST" action="{{ route('platform.subscriptions.invoices.store', $subscription) }}">@csrf<label class="block text-xs font-semibold">{{ __('platform.subscriptions.record_invoice') }}</label><input class="mt-1 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="reference" placeholder="{{ __('platform.subscriptions.invoice_reference') }}" required><input class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="amount" type="number" min="0.01" step="0.01" placeholder="{{ __('platform.subscriptions.amount') }}" required><div class="mt-2 grid grid-cols-2 gap-2"><input class="min-h-11 rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="billing_period_start" type="datetime-local" required><input class="min-h-11 rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="billing_period_end" type="datetime-local" required></div><div class="mt-2 grid grid-cols-2 gap-2"><input class="min-h-11 rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="payment_date" type="datetime-local" required><select class="min-h-11 rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="payment_method"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card_terminal">Card terminal</option><option value="other">Other</option></select></div><textarea class="mt-2 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2 py-2" name="notes" placeholder="{{ __('platform.subscriptions.notes') }}"></textarea><input class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] bg-[var(--pn-surface)] px-2" name="reason" placeholder="{{ __('platform.subscriptions.reason') }}" required><button class="mt-2 min-h-11 rounded-[10px] bg-[var(--pn-primary)] px-3 font-semibold text-[var(--pn-surface)]" type="submit">{{ __('platform.subscriptions.record_invoice') }}</button></form>
                </div></details>@else<span class="text-[var(--pn-ink-muted)]">{{ __('platform.subscriptions.history') }}</span>@endif</td></tr> @endforeach
            </tbody></table></div>@endif
            @if($subscriptions->hasPages())<div class="mt-4">{{ $subscriptions->links() }}</div>@endif
        </section>
        <section class="mt-10 grid gap-8 lg:grid-cols-2"><div><h2 class="text-lg font-bold">{{ __('platform.subscriptions.recent_invoices') }}</h2><p class="mt-1 text-sm text-[var(--pn-ink-muted)]">{{ __('platform.subscriptions.manual_billing_description') }}</p><div class="mt-3 overflow-x-auto rounded-[14px] border border-[var(--pn-border)] bg-[var(--pn-surface)]"><table class="w-full text-sm"><thead class="bg-[var(--pn-surface-subtle)]"><tr><th class="px-3 py-2 text-start">{{ __('platform.subscriptions.invoice_reference') }}</th><th class="px-3 py-2 text-start">{{ __('platform.subscriptions.tenant') }}</th><th class="px-3 py-2 text-start">{{ __('platform.subscriptions.amount') }}</th></tr></thead><tbody class="divide-y divide-[var(--pn-border)]">@forelse($invoices as $invoice)<tr><td class="px-3 py-3"><bdi dir="ltr">{{ $invoice->reference }}</bdi></td><td class="px-3 py-3">{{ $invoice->tenant?->name }}</td><td class="px-3 py-3 tabular-nums"><bdi dir="ltr">{{ $money($invoice->amount_minor) }} {{ $invoice->currency }}</bdi></td></tr>@empty<tr><td class="px-3 py-3 text-[var(--pn-ink-muted)]" colspan="3">{{ __('platform.subscriptions.empty') }}</td></tr>@endforelse</tbody></table></div></div><div><h2 class="text-lg font-bold">{{ __('platform.subscriptions.audit_history') }}</h2><div class="mt-3 max-h-72 overflow-auto rounded-[14px] border border-[var(--pn-border)] bg-[var(--pn-surface)] p-3 text-sm">
            @if($audits->isEmpty()) <p class="text-[var(--pn-ink-muted)]">{{ __('platform.subscriptions.empty') }}</p>
            @else @foreach($audits as $subjectAudits) @foreach($subjectAudits as $audit)<div class="border-b border-[var(--pn-border)] py-2 last:border-0"><strong>{{ $audit->action }}</strong><span class="ms-2 text-[var(--pn-ink-muted)]">{{ $audit->occurred_at }}</span><span class="mt-1 block text-[var(--pn-ink-muted)]">{{ $audit->reason_code }}</span></div>@endforeach @endforeach @endif
        </div></div></section>
    </main>
    <script>const subscriptionAssign = document.querySelector('[data-subscription-assign-form]'); subscriptionAssign?.querySelector('[data-assign-tenant]')?.addEventListener('change', function () { subscriptionAssign.querySelector('[data-assign-current-subscription]').value = this.selectedOptions[0]?.dataset.currentSubscription || ''; }); subscriptionAssign?.addEventListener('submit', function (event) { const tenant = this.querySelector('[data-assign-tenant]').value; if (!tenant) { event.preventDefault(); return; } this.action = this.action.replace('__TENANT__', tenant); });</script>
@endsection
