@extends('layouts.app')

@section('title', __('operational_notifications.page_title').' · PlayNexus')

@section('content')
<main class="mx-auto min-h-screen max-w-[1440px] px-4 py-6 sm:px-6">
    <header class="border-b border-[var(--pn-border)] pb-5"><h1 class="text-2xl font-bold">{{ __('operational_notifications.page_title') }}</h1><p class="mt-1 text-sm text-[var(--pn-ink-muted)]">{{ __('operational_notifications.description') }}</p></header>
    <form class="mt-5 grid gap-4 rounded-[14px] border border-[var(--pn-border)] bg-[var(--pn-surface)] p-5 sm:grid-cols-2 lg:grid-cols-4" method="GET">
        <div><label class="block text-sm font-semibold" for="branch_id">{{ __('operational_notifications.branch') }}</label><select class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] px-3" id="branch_id" name="branch_id"><option value="">{{ __('operational_notifications.all_branches') }}</option>@foreach ($branches as $branch)<option value="{{ $branch->id }}" @selected((string) request('branch_id') === (string) $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
        <div><label class="block text-sm font-semibold" for="purpose">{{ __('operational_notifications.purpose') }}</label><select class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] px-3" id="purpose" name="purpose"><option value="">{{ __('operational_notifications.all') }}</option>@foreach ($availablePurposes as $purpose)<option value="{{ $purpose }}" @selected(request('purpose') === $purpose)>{{ __('operational_notifications.purposes.'.$purpose) }}</option>@endforeach</select></div>
        <div><label class="block text-sm font-semibold" for="status">{{ __('operational_notifications.status') }}</label><select class="mt-2 min-h-11 w-full rounded-[10px] border border-[var(--pn-border)] px-3" id="status" name="status"><option value="">{{ __('operational_notifications.all') }}</option>@foreach (['queued','sent','delivered','failed_retryable','failed_permanent','stale'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ __('operational_notifications.statuses.'.$status) }}</option>@endforeach</select></div>
        <button class="min-h-11 self-end rounded-[10px] bg-[var(--pn-primary)] px-4 font-semibold text-white" type="submit">{{ __('operational_notifications.apply') }}</button>
    </form>
    <section class="mt-6" aria-labelledby="notification-results"><h2 class="text-lg font-bold" id="notification-results">{{ __('operational_notifications.results') }}</h2>
        @if ($messages->isEmpty())<div class="mt-3 rounded-[14px] border border-dashed border-[var(--pn-border-strong)] bg-[var(--pn-surface)] p-8 text-center text-[var(--pn-ink-muted)]">{{ __('operational_notifications.empty') }}</div>
        @else<div class="mt-3 overflow-x-auto rounded-[14px] border border-[var(--pn-border)] bg-[var(--pn-surface)]" data-pn-responsive-table><table class="w-full min-w-[820px] text-sm"><thead class="bg-[var(--pn-surface-subtle)]"><tr>@foreach (['created','purpose','branch','destination','status','attempts'] as $column)<th class="px-4 py-3 text-start" scope="col">{{ __('operational_notifications.'.$column) }}</th>@endforeach</tr></thead><tbody class="divide-y divide-[var(--pn-border)]">@foreach ($messages as $message)<tr><td class="px-4 py-3"><time dir="ltr">{{ $message->created_at->utc()->format('Y-m-d H:i') }} UTC</time></td><td class="px-4 py-3">{{ __('operational_notifications.purposes.'.$message->purpose) }}</td><td class="px-4 py-3">{{ $message->branch?->name }}</td><td class="px-4 py-3"><bdi dir="ltr">{{ $message->destination_masked ?: '—' }}</bdi></td><td class="px-4 py-3"><span class="inline-flex rounded-full bg-[var(--pn-primary-soft)] px-3 py-1 font-semibold">{{ __('operational_notifications.statuses.'.$message->status) }}</span></td><td class="px-4 py-3 tabular-nums">{{ $message->attempts_count }}</td></tr>@endforeach</tbody></table></div><div class="mt-4">{{ $messages->links() }}</div>@endif
    </section>
</main>
@endsection
